version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.4-node-jessie
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - run:         
         command: echo 'Hello World!'         
      

  bundle_dependencies:
    docker:
      - image: circleci/ruby:2.4-node-jessie
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - run:         
         command: echo 'Hello bundle dependencies' 

  rake_test:
    docker:
      - image: circleci/ruby:2.4-node-jessie
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - run:         
         command: echo 'Hello bundle dependencies' 

  deploy:
    machine:
        enabled: true
    working_directory: ~/circleci-demo-workflows    
    steps:      
      - run:          
          command: echo 'deploying now...'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - rake_test:
          requires:
            - bundle_dependencies      
      - deploy:
          requires:
            - rake_test
            - bundle_dependencies
