version: 2.1
orbs:
  jira: circleci/jira@1.0.5

jobs:
  checkout_code:
    working_directory: ~/circleci-demo-workflows
    docker:
     - image: alpine:3.7
    steps:
      - run:         
         command: echo 'Hello World!'         
      

  bundle_dependencies:
    working_directory: ~/circleci-demo-workflows
    docker:
     - image: alpine:3.7
    steps:
      - run:         
         command: echo 'Hello bundle dependencies' 

  rake_test:
    working_directory: ~/circleci-demo-workflows
    docker:
     - image: alpine:3.7
    steps:
      - run:         
         command: echo 'Hello performing tests...' 

  deploy:
    machine:
        enabled: true
    working_directory: ~/circleci-demo-workflows    
    steps:      
      - run:          
          command: echo 'deploying now...'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
          post-steps:
            - jira/notify:
                token: 6eae3b1fb21b82b6cdc7492fbea6d8f05a9f501d
                job-type: build                
      - rake_test:
          requires:
            - bundle_dependencies      
      - deploy:
          requires:
            - rake_test
            - bundle_dependencies
          post-steps:
            - jira/notify:
                token: 6eae3b1fb21b82b6cdc7492fbea6d8f05a9f501d
                job-type: deployment
                environment-type: development
                
